### Лабораторная работа №3

#### Импорты

In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
import plotly.graph_objects as go
import plotly.figure_factory as ff
from scipy.cluster.hierarchy import linkage
from ipywidgets import widgets

#### Набор данных «Ирисы Фишера»

##### Получение и рассмотренеи данных

In [2]:
iris_dict: dict = load_iris()
iris_dict.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
iris_df = pd.DataFrame(data=iris_dict['data'], columns=iris_dict['feature_names'])
iris_df['target'] = iris_dict['target']

In [4]:
iris_df.sample(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
70,5.9,3.2,4.8,1.8,1
43,5.0,3.5,1.6,0.6,0
109,7.2,3.6,6.1,2.5,2
144,6.7,3.3,5.7,2.5,2
108,6.7,2.5,5.8,1.8,2

In [5]:
iris_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [6]:
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

##### Преобразование данных

In [7]:
y_iris = iris_df['target']
X_iris = iris_df.drop(columns=['target'])

In [8]:
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

In [9]:
scaler_class = StandardScaler()
X_train_iris_scaled = scaler_class.fit_transform(X_train_iris)
X_test_iris_scaled = scaler_class.transform(X_test_iris)

In [10]:
scaler_сlust = StandardScaler()
X_iris_scaled = scaler_сlust.fit_transform(X_iris)

In [11]:
def show_metrics(y_train_pred, y_test_pred, y_train=y_train_iris, y_test=y_test_iris):
    pass

##### Классификация набора алгоритмом k-ближайших соседей

In [12]:
kn_class_params = {
    'n_neighbors': [i for i in range(1, 21)],
    'algorithm': ['ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [30, 40, 50, 60]
}
kn_class = KNeighborsClassifier()
grid_search_kn_class = GridSearchCV(kn_class, kn_class_params, cv=5)
grid_search_kn_class.fit(X_train_iris_scaled, y_train_iris)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [30, 40, 50, 60],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20]})

In [13]:
kn_class_y_train_pred = grid_search_kn_class.best_estimator_.predict(X_train_iris_scaled)
kn_class_y_test_pred = grid_search_kn_class.best_estimator_.predict(X_test_iris_scaled)

##### Классификация набора алгоритмом «случайный лес»

In [15]:
rf_class_params = {
    'n_estimators': [i for i in range(50, 300, 100)],
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 5, 10, 15, 20, 30, 50],
    'max_features': ['sqrt', 'log2', None]
}
rf_class = RandomForestClassifier()
grid_search_rf_class = GridSearchCV(rf_class, rf_class_params, cv=5)
grid_search_rf_class.fit(X_train_iris_scaled, y_train_iris)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [None, 5, 10, 15, 20, 30, 50],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [50, 150, 250]})

In [17]:
rf_class_y_train_pred = grid_search_rf_class.best_estimator_.predict(X_train_iris_scaled)
rf_class_y_test_pred = grid_search_rf_class.best_estimator_.predict(X_test_iris_scaled)

##### Классификация набора машинами опорных векторов (SVM)

In [18]:
svc_params = {
    'C': [i for i in range(1, 7)],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'degree': [i for i in range(1, 11)],
}

svc = SVC()
grid_search_svc = GridSearchCV(svc, svc_params, cv=5)
grid_search_svc.fit(X_train_iris_scaled, y_train_iris)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 2, 3, 4, 5, 6],
                         'degree': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [19]:
svc_y_train_pred = grid_search_svc.best_estimator_.predict(X_train_iris_scaled)
svc_y_test_pred = grid_search_svc.best_estimator_.predict(X_test_iris_scaled)

##### Кластеризация набора алгоритмом k-средних

Применение алгоритма

In [20]:
inertia = []
cluster_centers_list = []
labels_list = []
n_clusters_list = [n_clusters for n_clusters in range(1, 11)]
for n_clusters in n_clusters_list:
    kmeans_сlust_model = KMeans(n_clusters=n_clusters)
    kmeans_сlust_model.fit(X_iris_scaled)
    inertia.append(kmeans_сlust_model.inertia_)
    cluster_centers_list.append(kmeans_сlust_model.cluster_centers_)
    labels_list.append(kmeans_сlust_model.labels_)

Визуализация распределения

In [21]:
# https://plotly.com/python/figurewidget-app/

feature_names_iris = list(X_iris.columns)

n_clusters_slider = widgets.IntSlider(
    value=n_clusters_list[0],
    min=n_clusters_list[0],
    max=n_clusters_list[-1],
    step=1.0,
    description='Количество кластеров:',
)

show_cluster_centers = widgets.Checkbox(
    description='Показывать центр кластеров: ',
    value=True,
)

container = widgets.HBox(children=[show_cluster_centers, n_clusters_slider])

y_feature = widgets.Dropdown(
    description='Признак Y:   ',
    value=feature_names_iris[0],
    options=feature_names_iris
)

x_feature = widgets.Dropdown(
    description='Признак X:   ',
    value=feature_names_iris[1],
    options=feature_names_iris
)

In [22]:
g = go.FigureWidget(layout=dict(width=1200, height=500))
g.add_scatter(
    mode='markers',
    marker=dict(colorscale='Viridis', showscale=False, size=10, opacity=0.75),
    name='Точка',
    hovertemplate='Точка кластера: %{text}<br>X: %{x}<br>Y: %{y}<extra></extra>'
)
g.add_scatter(
    mode='markers',
    marker=dict(symbol='x', size=12, color='red'),
    name='Центр кластера',
    hovertemplate='Центр кластера: %{text}<br>X: %{x}<br>Y: %{y}<extra></extra>'
)

def response(change=None):
    # Получаем текущие значения виджетов
    x_name = x_feature.value
    y_name = y_feature.value
    x_idx = feature_names_iris.index(x_name)
    y_idx = feature_names_iris.index(y_name)
    n = n_clusters_slider.value
    show = show_cluster_centers.value

    # Индекс для выбранного k в списке n_clusters_list
    idx = n_clusters_list.index(n)

    # Берём метки кластеров и центры
    labels = labels_list[idx].tolist()
    centers = cluster_centers_list[idx]

    # Координаты точек по выбранным признакам
    x_vals = X_iris_scaled[:, x_idx].tolist()
    y_vals = X_iris_scaled[:, y_idx].tolist()

    # Координаты центров по выбранным признакам
    x_centers = centers[:, feature_names_iris.index(x_name)].tolist()
    y_centers = centers[:, feature_names_iris.index(y_name)].tolist()

    # Обновляем график (batch_update для производительности)
    with g.batch_update():
        # Точки
        g.data[0].x = x_vals
        g.data[0].y = y_vals
        g.data[0].marker.color = labels
        g.data[0].text = labels
        # Центры
        g.data[1].x = x_centers
        g.data[1].y = y_centers
        g.data[1].text = [str(i) for i in range(n)]
        g.data[1].visible = show
        # Подписи осей и заголовок
        g.layout.xaxis.title = x_name
        g.layout.yaxis.title = y_name
        g.layout.title = f'Кластеризация набора "Ирисы Фишера" (n_clusters={n})'

x_feature.observe(response, names='value')
y_feature.observe(response, names='value')
n_clusters_slider.observe(response, names='value')
show_cluster_centers.observe(response, names='value')

response()

container = widgets.HBox([show_cluster_centers, n_clusters_slider])
container2 = widgets.HBox([x_feature, y_feature])
widgets.VBox([container, container2, g])

VBox(children=(HBox(children=(Checkbox(value=True, description='Показывать центр кластеров: '), IntSlider(valu…

Визуализация метода локтя

In [23]:
fig_kmeans_сlust_elbow_method = go.Figure()
fig_kmeans_сlust_elbow_method.add_trace(
    go.Scatter(x=n_clusters_list, y=inertia, mode='lines+markers', line=dict(color='red', width=2), marker=dict(color='red', size=10))
)
fig_kmeans_сlust_elbow_method.add_trace(
    go.Bar(x=n_clusters_list, y=inertia, marker_color='blue')
)
fig_kmeans_сlust_elbow_method.update_layout(
    title='Метод локтя "Ирисы Фишера"',
    xaxis_title='Число кластеров (n_clusters)',
    yaxis_title='Сумма внутрикластерных расстояний',
    xaxis=dict(tickmode='linear', dtick=1),
    barcornerradius=20,
    showlegend=False
)
fig_kmeans_сlust_elbow_method.show()

##### Иерархическая кластеризация методом Уорда

Применение алгоритма

In [24]:
ward_clust = AgglomerativeClustering(n_clusters=3, linkage='ward')
ward_clust_labels = ward_clust.fit_predict(X_iris_scaled)

Визуализация дендрограммы

In [25]:
fig = ff.create_dendrogram(
    X_iris_scaled,
    labels=[f'{i} ({y_iris[i]})' for i in range(len(X_iris_scaled))],
    linkagefun=lambda x: linkage(x, method='ward'),
    orientation='bottom',
    color_threshold=10
)
fig.update_layout(
    title='Дендрограмма',
    xaxis_title='Кластеры',
    yaxis_title='Расстояние',
    width=1450,
    height=600
)
fig.show()